using JuMP, Gurobi
model = Model(Gurobi.Optimizer)
@variable(model, x1 >=0)
@variable(model, x2 >=0)
@objective(model, Max, 8x1+5x2)
@constraint(model,x1+x2<=6)
@constraint(model,9x1+5x2<=45)
JuMP.optimize!(model)
obj_value = JuMP.objective_value(model)
println("Objective value : ", obj_value)
println("x1 : ", JuMP.value(x1))
println("x2 : ", JuMP.value(x1))
